#!/bin/bash

# This script was generated by classpath.py.
# It can be "sourced" from within a bash shell script to set
# and export the CP environment variable; the Java CLASSPATH.
# Chris Joakim, 2018/06/17


curl -v http://localhost:8080/cosmosdb/zipcodes/87ed3026-9539-4c49-863d-4e54e60a8316


body='{ "pk": "test", "name": "x"}'

echo $body  | curl -i -X POST -H 'Content-type: application/json' -d @- 'http://localhost:8080/cosmosdb/zipcodes/'

