#!/bin/bash
# This script was generated by classpath.py.
# It can be executed to do a "jar -xvf" for each jar in the
# CLASSPATH, so as to produce a list of all dependent classes for analysis.
# Chris Joakim, 2018/06/17


echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.0.3.RELEASE/spring-boot-starter-web-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.0.3.RELEASE/spring-boot-starter-web-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter/2.0.3.RELEASE/spring-boot-starter-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter/2.0.3.RELEASE/spring-boot-starter-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot/2.0.3.RELEASE/spring-boot-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot/2.0.3.RELEASE/spring-boot-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.0.3.RELEASE/spring-boot-autoconfigure-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.0.3.RELEASE/spring-boot-autoconfigure-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.0.3.RELEASE/spring-boot-starter-logging-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.0.3.RELEASE/spring-boot-starter-logging-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.10.0/log4j-to-slf4j-2.10.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.10.0/log4j-to-slf4j-2.10.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/yaml/snakeyaml/1.19/snakeyaml-1.19.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/yaml/snakeyaml/1.19/snakeyaml-1.19.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.0.3.RELEASE/spring-boot-starter-json-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.0.3.RELEASE/spring-boot-starter-json-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.6/jackson-datatype-jdk8-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.6/jackson-datatype-jdk8-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.6/jackson-datatype-jsr310-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.6/jackson-datatype-jsr310-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.6/jackson-module-parameter-names-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.6/jackson-module-parameter-names-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.0.3.RELEASE/spring-boot-starter-tomcat-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.0.3.RELEASE/spring-boot-starter-tomcat-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.31/tomcat-embed-core-8.5.31.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.31/tomcat-embed-core-8.5.31.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.31/tomcat-embed-el-8.5.31.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.31/tomcat-embed-el-8.5.31.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.31/tomcat-embed-websocket-8.5.31.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.31/tomcat-embed-websocket-8.5.31.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.10.Final/hibernate-validator-6.0.10.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.10.Final/hibernate-validator-6.0.10.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-web/5.0.7.RELEASE/spring-web-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-web/5.0.7.RELEASE/spring-web-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-beans/5.0.7.RELEASE/spring-beans-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-beans/5.0.7.RELEASE/spring-beans-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-webmvc/5.0.7.RELEASE/spring-webmvc-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-webmvc/5.0.7.RELEASE/spring-webmvc-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-aop/5.0.7.RELEASE/spring-aop-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-aop/5.0.7.RELEASE/spring-aop-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-context/5.0.7.RELEASE/spring-context-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-context/5.0.7.RELEASE/spring-context-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-expression/5.0.7.RELEASE/spring-expression-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-expression/5.0.7.RELEASE/spring-expression-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.0.3.RELEASE/spring-boot-starter-test-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.0.3.RELEASE/spring-boot-starter-test-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test/2.0.3.RELEASE/spring-boot-test-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test/2.0.3.RELEASE/spring-boot-test-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.0.3.RELEASE/spring-boot-test-autoconfigure-2.0.3.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.0.3.RELEASE/spring-boot-test-autoconfigure-2.0.3.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/mockito/mockito-core/2.15.0/mockito-core-2.15.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/mockito/mockito-core/2.15.0/mockito-core-2.15.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy/1.7.11/byte-buddy-1.7.11.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy/1.7.11/byte-buddy-1.7.11.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy-agent/1.7.11/byte-buddy-agent-1.7.11.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy-agent/1.7.11/byte-buddy-agent-1.7.11.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/skyscreamer/jsonassert/1.5.0/jsonassert-1.5.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/skyscreamer/jsonassert/1.5.0/jsonassert-1.5.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-core/5.0.7.RELEASE/spring-core-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-core/5.0.7.RELEASE/spring-core-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-jcl/5.0.7.RELEASE/spring-jcl-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-jcl/5.0.7.RELEASE/spring-jcl-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-test/5.0.7.RELEASE/spring-test-5.0.7.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-test/5.0.7.RELEASE/spring-test-5.0.7.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/xmlunit/xmlunit-core/2.5.1/xmlunit-core-2.5.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/xmlunit/xmlunit-core/2.5.1/xmlunit-core-2.5.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure/1.11.1/azure-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure/1.11.1/azure-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-runtime/1.5.2/azure-client-runtime-1.5.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-runtime/1.5.2/azure-client-runtime-1.5.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/rest/client-runtime/1.5.2/client-runtime-1.5.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/rest/client-runtime/1.5.2/client-runtime-1.5.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/retrofit/2.1.0/retrofit-2.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/retrofit/2.1.0/retrofit-2.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp/3.4.2/okhttp-3.4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp/3.4.2/okhttp-3.4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okio/okio/1.9.0/okio-1.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okio/okio/1.9.0/okio-1.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.4.2/logging-interceptor-3.4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.4.2/logging-interceptor-3.4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.4.2/okhttp-urlconnection-3.4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.4.2/okhttp-urlconnection-3.4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/converter-jackson/2.1.0/converter-jackson-2.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/converter-jackson/2.1.0/converter-jackson-2.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.9.6/jackson-datatype-joda-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.9.6/jackson-datatype-joda-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.1.0/adapter-rxjava-2.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.1.0/adapter-rxjava-2.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-authentication/1.5.2/azure-client-authentication-1.5.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-authentication/1.5.2/azure-client-authentication-1.5.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-annotations/1.2.0/azure-annotations-1.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-annotations/1.2.0/azure-annotations-1.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-resources/1.11.1/azure-mgmt-resources-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-resources/1.11.1/azure-mgmt-resources-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-storage/1.11.1/azure-mgmt-storage-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-storage/1.11.1/azure-mgmt-storage-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-network/1.11.1/azure-mgmt-network-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-network/1.11.1/azure-mgmt-network-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-compute/1.11.1/azure-mgmt-compute-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-compute/1.11.1/azure-mgmt-compute-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-graph-rbac/1.11.1/azure-mgmt-graph-rbac-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-graph-rbac/1.11.1/azure-mgmt-graph-rbac-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-keyvault/1.11.1/azure-mgmt-keyvault-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-keyvault/1.11.1/azure-mgmt-keyvault-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault/1.0.0/azure-keyvault-1.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault/1.0.0/azure-keyvault-1.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-webkey/1.0.0/azure-keyvault-webkey-1.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-webkey/1.0.0/azure-keyvault-webkey-1.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batch/1.11.1/azure-mgmt-batch-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batch/1.11.1/azure-mgmt-batch-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-trafficmanager/1.11.1/azure-mgmt-trafficmanager-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-trafficmanager/1.11.1/azure-mgmt-trafficmanager-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-dns/1.11.1/azure-mgmt-dns-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-dns/1.11.1/azure-mgmt-dns-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-redis/1.11.1/azure-mgmt-redis-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-redis/1.11.1/azure-mgmt-redis-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-appservice/1.11.1/azure-mgmt-appservice-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-appservice/1.11.1/azure-mgmt-appservice-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/6.1.0/azure-storage-6.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/6.1.0/azure-storage-6.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-locks/1.11.1/azure-mgmt-locks-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-locks/1.11.1/azure-mgmt-locks-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-eventhub/1.11.1/azure-mgmt-eventhub-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-eventhub/1.11.1/azure-mgmt-eventhub-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cdn/1.11.1/azure-mgmt-cdn-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cdn/1.11.1/azure-mgmt-cdn-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-sql/1.11.1/azure-mgmt-sql-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-sql/1.11.1/azure-mgmt-sql-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerinstance/1.11.1/azure-mgmt-containerinstance-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerinstance/1.11.1/azure-mgmt-containerinstance-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerregistry/1.11.1/azure-mgmt-containerregistry-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerregistry/1.11.1/azure-mgmt-containerregistry-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerservice/1.11.1/azure-mgmt-containerservice-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerservice/1.11.1/azure-mgmt-containerservice-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cosmosdb/1.11.1/azure-mgmt-cosmosdb-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cosmosdb/1.11.1/azure-mgmt-cosmosdb-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-search/1.11.1/azure-mgmt-search-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-search/1.11.1/azure-mgmt-search-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-msi/1.11.1/azure-mgmt-msi-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-msi/1.11.1/azure-mgmt-msi-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-monitor/1.11.1/azure-mgmt-monitor-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-monitor/1.11.1/azure-mgmt-monitor-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-servicebus/1.11.1/azure-mgmt-servicebus-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-servicebus/1.11.1/azure-mgmt-servicebus-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batchai/1.11.1/azure-mgmt-batchai-1.11.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batchai/1.11.1/azure-mgmt-batchai-1.11.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/1.16.1/azure-documentdb-1.16.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/1.16.1/azure-documentdb-1.16.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/uuid/java-uuid-generator/3.1.4/java-uuid-generator-3.1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/uuid/java-uuid-generator/3.1.4/java-uuid-generator-3.1.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/json/json/20140107/json-20140107.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/json/json/20140107/json-20140107.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/1.2.5/azure-servicebus-1.2.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/1.2.5/azure-servicebus-1.2.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.22.0/proton-j-0.22.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.22.0/proton-j-0.22.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.53/bcpkix-jdk15on-1.53.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.53/bcpkix-jdk15on-1.53.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.53/bcprov-jdk15on-1.53.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.53/bcprov-jdk15on-1.53.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.3.0/adal4j-1.3.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.3.0/adal4j-1.3.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/5.24.1/oauth2-oidc-sdk-5.24.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/5.24.1/oauth2-oidc-sdk-5.24.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/mail/mail/1.4.7/mail-1.4.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/mail/mail/1.4.7/mail-1.4.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.4.3/lang-tag-1.4.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.4.3/lang-tag-1.4.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/5.12/nimbus-jose-jwt-5.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/5.12/nimbus-jose-jwt-5.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-csv/1.5/commons-csv-1.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-csv/1.5/commons-csv-1.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.5.0/commons-pool2-2.5.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.5.0/commons-pool2-2.5.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar >> doc/jar_contents.txt

